### ISSUE TITLE
Module prevents config.js file from running

### ISSUE THREAD

**Issue by martyg33** [cowboysdude/MMM-NPR#3]
Hey I have just installed the module and updated my config.js file, whenever I run the mirror I am given a config.js syntax error. It is narrowed down to this specific module. Whenever I comment out the disabled:t line, I am able to run the mirror but the npr module simply does not show up. Do you have any ideas?

My code is as follows:
{
disabled:t,
module: "MMM-NPR",
position: "bottom_center"
config: {
type: 'us',
}
},

**Comment by cowboysdude** [comment]
{
disabled:t,  // <-  That's why change the t to false ......
module: "MMM-NPR",
position: "bottom_center"
config: {
type: 'us',
}
},

I use shorthand for true or false at the top of my config I have this
var t = true;
var f = false;

:)

It won't work on yours PLUS even if it did you have it disabled when you
use t

So change that line to this:
disabled: false,

and it should run :)

**Comment by martyg33** [comment]
I understand haha thank you for the correction. So everything runs now, but the module simply does not show up. Do you have any other ideas?

**Comment by cowboysdude** [comment]
Run your mirror in npm start dev and see if you're getting any errors

**Comment by martyg33** [comment]
I am getting quite a few of the same error. It is:
[1023:1128/135200.047482:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)

**Comment by cowboysdude** [comment]
Not sure what that's about i would have to see it.  If you have team viewer
installed that would allow me to do that

**Comment by cowboysdude** [comment]
No answer back so if you continue having issues please reopen.
